# Generated by Django 3.2.11 on 2022-01-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('Dev.to', 'Dev.to'), ('HackerNews', 'HackerNews')], max_length=10)),
                ('source_link', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('publish_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
