# Generated by Django 3.2.11 on 2022-01-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='source',
            field=models.CharField(max_length=255),
        ),
    ]
