name: Build CI

on:
  push:
    branches: [ deployment ]

jobs:

  build:

    env: 
      DEBUG: False
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      POSTGRES_DB: ${{ secrets.DB_NAME }}
      POSTGRES_USER: ${{ secrets.DB_USER }}
      POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASSWORD }}
      CELERY_BROKER_URL: ${{ secrets.CELERY_URL }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose --file=docker-compose-gh.yml build
    - name: Pass security checks
      run: docker-compose --file=docker-compose-gh.yml run --rm app sh -c "python manage.py check --deploy --fail-level=ERROR"
    - name: Perform tests
      run: docker-compose --file=docker-compose-gh.yml run --rm app sh -c "python manage.py test"
